### ISSUE TITLE
Support for macOS 10.13 High Sierra (beta)

### ISSUE THREAD

**Issue by raisedadead** [stephennancekivell/brew-update-notifier#1]
```shell
$ curl -s https://raw.githubusercontent.com/stephennancekivell/brew-update-notifier/master/install.sh | sh
Installing Scripts
Installing Dependency
terminal-notifier: A full installation of Xcode.app is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.
Adding Crontab to run every hour
crontab: no crontab for raisedadead
```

**Comment by stephennancekivell** [comment]
Hi, Thanks for raising the issue. Would you mind trying to fix it by installing Xcode as described in the error message. Then trying again.

**Comment by raisedadead** [comment]
Hi, thanks a lot for getting back to me. Yes, while I understand that installing the XCode app will resolve the issue, I am afraid this is not something desirable for the end users.

The XCode app is about 4.5 GB download from the app store, and I am a bit hesitant to do that for a notification application.

Of course, I can help with debugging and any assistance required, but what I believe is that can this be rather built and released as binaries.

Thanks again for the great work!

**Comment by raisedadead** [comment]
Sorry, Just cleaning up my issues queue. Thanks for your help & support.
